  version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/openjdk:11.0.3-jdk-stretch
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout # check out the code in the project directory
        - run:
            name: "Building application"
            command: ./gradlew clean build
